---
- name: Install AppDynamics Machine Agent
  hosts: all
  become: yes
  connection: local   # <── prevents SSH, runs directly on the node

  vars:
    appd_controller_host: "{{ appd_controller_url }}"
    appd_account_name: "{{ appd_username }}"
    appd_account_access_key: "{{ appd_access_key }}"
    appd_agent_home: "/opt/appdynamics/machine-agent"

  tasks:
    - name: Ensure AppDynamics agents collection is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection install appdynamics.agents
      changed_when: false

    - name: Install Machine Agent using official role
      ansible.builtin.include_role:
        name: appdynamics.agents.machine
      vars:
        controller_host: "{{ appd_controller_host }}"
        account_name: "{{ appd_account_name }}"
        account_access_key: "{{ appd_account_access_key }}"
        install_dir: "{{ appd_agent_home }}"
        enable_service: true
